### ISSUE TITLE
Invalid combination of arguments for vid_feats

### ISSUE THREAD

**Issue by GXNU156489** [AndresPMD/StacMR#4]
After I use python3 to run the code, I get an error on line 57 of EncoderRnn.py. It prompts me that the parameter combination I entered is invalid. The dataset I use comes from here：https://drive.google.com/file/d/1K66sBXZ9XcfDke7pg8DBmA8nBpnp-z9r/view?usp=sharing

The specific error information is as follows：
![image](https://user-images.githubusercontent.com/36919834/167279544-d53b2cf2-783d-4216-b588-17118ff5d165.png)

**Comment by AndresPMD** [comment]
@GXNU156489 

This code was tested on python 2.7. Sorry for the bug, but you may have to adjust it to python 3.

**Comment by GXNU156489** [comment]
@AndresPMD Thank you for your reply, I have solved this problem, it is the wrong type of bidrectional
