### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by aleks73337** [AndresPMD/StacMR#5]
Hi, @AndresPMD! Can you please share the code for visualization? I saw in the article that you did that for text to image and image to text. 
![image](https://user-images.githubusercontent.com/32843048/168471635-f99c6d70-0f15-49d4-a9c2-38766063cdac.png)

**Comment by AndresPMD** [comment]
Hello @aleks73337,

I currently do not have a visualization script at hand. But overall the visualization is pretty simple.
You just need to understand the data format. The test set contains an ordered list of images and captions associated with them in a txt file.

You need to compute the similarity between images and captions by using the dot product and with those indexes you can refer to the text or the images used.
